convoy-volumes:
  name: convoy-volumes
  image: elcolio/os-convoy
  container_name: convoy-volumes
  privileged: true
  labels:
    io.rancher.os.scope: system
    io.rancher.os.createonly: true
  volumes:
    - /opt/lib/convoy:/opt/lib/convoy

convoy:
  name: convoy
  image: elcolio/os-convoy
  container_name: convoy
  privileged: true
  labels:
    io.rancher.os.scope: system
  volumes_from:
    - all-volumes
    - convoy-volumes
  restart: always
