convoy-volumes:
  image: elcolio/os-convoy
  container_name: convoy-volumes
  privileged: true
  labels:
    io.rancher.os.scope: system
  volumes:
    - /opt/lib/convoy:/opt/lib/convoy
    - /opt/bin/convoy:/opt/bin/convoy:ro
    - /var/run/convoy:/var/run/convoy
  restart: always

convoy:
  image: elcolio/os-convoy
  container_name: convoy
  privileged: true
  labels:
    io.rancher.os.scope: system
  volumes_from:
    - all-volumes
    - convoy-volumes
  restart: always
