convoy:
  name: convoy
  image: elcolio/os-convoy
  container_name: convoy
  privileged: true
  labels:
    io.rancher.os.scope: system
  volumes:
    - /opt/lib/convoy:/opt/lib/convoy
  volumes_from:
    - all-volumes
  restart: always
