weave:
  image: elcolio/os-weave:v0.4.3-dev
  container_name: weave
  privileged: true
  labels:
    io.rancher.os.scope: system
    io.rancher.os.after: docker,console
  volumes_from:
    - all-volumes
  net: host
